
- name: Include Sheepdog Variables
  include_vars: ./vars/sheepdog.yml

- name: Install Compile-time Dependencies
  apt:
    name: [automake,autoconf,pkg-config,build-essential,liburcu-dev,libtool,libcorosync-common-dev,libcpg-dev,libcfg-dev,yasm,libzookeeper-mt-dev]
    state: latest
    update_cache: yes


- name: Download Sources
  get_url: url={{ sheepdog.url }} dest={{ sheepdog.project_dir }}/{{ sheepdog.file }}

# - name: Unzip Sources
#   shell: tar xvzf {{ sheepdog.project_dir }}/{{ sheepdog.file }}

- name: Extract foo.tgz into /var/lib/foo
  ansible.builtin.unarchive:
    src: /home/ubuntu/{{ sheepdog.file }}
    dest: /home/ubuntu/
    remote_src: yes

- name: Run ./autogen Script
  shell: /home/ubuntu/sheepdog-0.9.3/autogen


- name: Run ./configure Script
  shell: /home/ubuntu/sheepdog-0.9.3/configure --enable-zookeeper

- name: Make Sheepdog
  command: chdir=/home/ubuntu/sheepdog-0.9.3 make install
