- name: Copy Code
  ansible.builtin.copy:
    src: ../../external-API
    dest: /root
    owner: root
    group: root
    mode: '0755'

- name: Install dependencies
  command: chdir=/root/external-API npm install

- name: Install pm2 
  command: npm i -g pm2 

- name: Run External API Code 
  command: chdir=/root/external-API pm2 start app.js