- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: ../../internal-API
    dest: /root
    owner: root
    group: root
    mode: '0755'

- name: Install dependencies
  command: chdir=/root/internal-API npm install

- name: Run Internal API Code 
  command: chdir=/root/internal-API pm2 restart app.js