---
- name: Configure DNS
  hosts: all
  remote_user: root
  tasks:
    - name: Adding Shecan DNS Nameserver to /etc/resolv.conf
      include: ./shecan-dns/dns.yaml

# ------------------------------------------------------------------------------

# - name: Libvirt
#   hosts:
#     - virtualization

#   remote_user: root
#   tasks:
  
#     - name: Install Qemu
#       include: ./qemu/libvirt-install.yml

# ------------------------------------------------------------------------------

# - name: Ceph
#   hosts:
#     - storage-monitor

#   remote_user: root
#   tasks:

#     - name: Create RBD Pool
#       include: ./ceph/pool-create.yml

# ------------------------------------------------------------------------------

# - name: Storage Pool
#   hosts:
#     - virtualization

#   remote_user: root
#   tasks:

#     - name: Create Slave Bridge
#       include: ./qemu/bridge-create.yml

#     - name: Create Libvirt Storage Pool
#       include: ./qemu/libvirt-storage.yml

# ------------------------------------------------------------------------------

- name: Database
  hosts:
    - database

  remote_user: root
  tasks:

    - name: Install Docker
      include: ./docker/docker-install.yml

    - name: Create Redis and Postgres Containers
      include: ./database/database-install.yml

# ------------------------------------------------------------------------------





# - name: Install Nginx on manager
#   hosts:
#     - manager
#   remote_user: root
#   tasks:
#     # - name: Install Nginx on Ubuntu
#     #   include: ./nginx/nginx-install.yml
#     #   when: (ansible_facts['distribution'] == "Ubuntu")
    
#     # - name: Create Keys and Passwords for Nginx on Ubuntu
#     #   include: ./nginx/auth.yml
#     #   when: (ansible_facts['distribution'] == "Ubuntu")
    
#     - name: Configure Nginx  
#       include: ./nginx/nginx-config.yml
#       when: (ansible_facts['distribution'] == "Ubuntu")
    
#   handlers:
#     - name: Start Nginx
#       service:
#         name: nginx
#         state: started

#     - name: Restart Nginx
#       service:
#         name: nginx
#         state: restarted

...