---
# - name: Configure DNS
#   hosts:
#     - storage-test
#   remote_user: root
#   tasks:
#     - name: Adding Shecan DNS Nameserver to /etc/resolv.conf
#       include: ./shecan-dns/dns.yaml

# ------------------------------------------------------------------------------
# - name: Sheepdog
#   hosts:
#     - storage-test

#   remote_user: root
#   tasks:
#     - name: Install Sheepdog
#       include: ./sheepdog/sheep-install.yml

# ------------------------------------------------------------------------------

#- name: Configure Cluster Manager
#  hosts:
#    - cluster-manager-test

#  remote_user: root
#  tasks:
#     - name: Install Java
#       include: ./java/java-install.yml
#     - name: Install Zookeeper
#       include: ./zookeeper/zoo-install.yml

#     - name: Set Zookeeper ID
#       copy: >
#         content={{ item.0 + 1 }}
#         dest=/var/lib/zookeeper/myid
#       with_indexed_items: "{{groups['cluster-manager-test']}}"
#       when: item.1 == "{{inventory_hostname}}"
    
#    - name: Start Zookeeper
#      command: chdir=/usr/share/zookeeper/bin ./zkServer.sh start
    
# ------------------------------------------------------------------------------

# - name: Sheepdog
#   hosts:
#     - storage-test

#   remote_user: root
#   tasks:
#     - name: Config Sheepdog Cluster
#       include: ./sheepdog/sheep-config.yml

# ------------------------------------------------------------------------------

# - name: Qemu
#   hosts:
#     - qemu-test

#   remote_user: root
#   tasks:
#     - name: Create Slave Bridge
#       include: ./qemu/bridge-create.yml

# ------------------------------------------------------------------------------

- name: Install Nginx on manager
  hosts:
    - manager
  remote_user: root
  tasks:
    # - name: Install Nginx on Ubuntu
    #   include: ./nginx/nginx-install.yml
    #   when: (ansible_facts['distribution'] == "Ubuntu")
    
    # - name: Create Keys and Passwords for Nginx on Ubuntu
    #   include: ./nginx/auth.yml
    #   when: (ansible_facts['distribution'] == "Ubuntu")
    
    - name: Configure Nginx  
      include: ./nginx/nginx-config.yml
      when: (ansible_facts['distribution'] == "Ubuntu")
    
  handlers:
    - name: Start Nginx
      service:
        name: nginx
        state: started

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

...