---
# - name: Configure DNS
#   hosts: all
#   remote_user: root
#   tasks:
#     - name: Adding Shecan DNS Nameserver to /etc/resolv.conf
#       include: ./shecan-dns/dns.yaml

# ------------------------------------------------------------------------------

# - name: Libvirt
#   hosts:
#     - virtualization

#   remote_user: root
#   tasks:
  
#     - name: Install Libvirt
#       include: ./libvirt/libvirt-install.yml

# ------------------------------------------------------------------------------

# - name: Ceph
#   hosts:
#     - storage-monitor

#   remote_user: root
#   tasks:

#     - name: Create RBD Pool
#       include: ./ceph/pool-create.yml

# ------------------------------------------------------------------------------

# - name: Storage Pool
#   hosts:
#     - virtualization

#   remote_user: root
#   tasks:

#     - name: Create Libvirt Storage Pool
#       include: ./libvirt/libvirt-storage.yml

# ------------------------------------------------------------------------------

# - name: Virual Machine Configuration
#   hosts:
#     - virtualization

#   remote_user: root
#   tasks:

#     - name: Create Libvirt Config Files
#       include: ./libvirt/libvirt-vm.yml

# ------------------------------------------------------------------------------
# - name: Database
#   hosts:
#     - database

#   remote_user: root
#   tasks:

#     - name: Install Docker
#       include: ./docker/docker-install-centos.yml

#     - name: Create Redis and Postgres Containers
#       include: ./database/database-install.yml

# ------------------------------------------------------------------------------

# - name: Node.js
#   hosts: 
#     - external-API
#     - internal-API

#   remote_user: root
#   tasks:
#     - name: Install Node.js
#       include: ./node/node-install.yml

# ------------------------------------------------------------------------------

# - name: External APIs
#   hosts: external-API
#   remote_user: root
#   tasks:
    
#     - name: Copy and Run Code
#       include: ./api/external-api.yml

#     # - name: Update and Restart Code
#     #   include: ./api/external-api-update.yml


# ------------------------------------------------------------------------------

# - name: Internal APIs
#   hosts: internal-API
#   remote_user: root
#   tasks:
    
#     - name: Copy and Run Code
#       include: ./api/internal-api.yml

#     # - name: Update and Restart Code
#     #   include: ./api/internal-api-update.yml


# ------------------------------------------------------------------------------

- name: HAProxy
  hosts: 
    - internal-HA
  remote_user: root
  tasks:
    # - name: Install HAProxy
    #   include: ./haproxy/haproxy-install.yml
    
    - name: Configure HAProxy
      include: ./haproxy/haproxy-internal-config.yml

# ------------------------------------------------------------------------------

# - name: HAProxy
#   hosts: 
#     - external-HA
#   remote_user: root
#   tasks:
#     - name: Install HAProxy
#       include: ./haproxy/haproxy-install.yml
    
#     - name: Configure HAProxy
#       include: ./haproxy/haproxy-external-config.yml

# ------------------------------------------------------------------------------


# - name: Monitoring
#   hosts: 
#     - monitoring

#   remote_user: root
#   tasks:
#     # - name: Install Docker
#     #   include: ./docker/docker-install-ubuntu.yml

#     - name: Create Prometheus and Grafana Containers
#       include: ./monitoring/mon-tools-install.yml


...