version: '3'
services:
    prometheus:
        image: prom/prometheus:latest

        # volumes:
        #     - /etc/prometheus:/etc/prometheus
        #     - /prometheus:/prometheus

        command:
            - '-config.file=/etc/prometheus/prometheus.yml'
            - '-storage.local.path=/prometheus'
            - '-alertmanager.url=http://alertmanager:9093'
        ports: 
            - 9090:9090

    grafana:
        image: grafana/grafana:latest
        restart: unless-stopped
        links:
            - prometheus:prometheus
        # volumes:
        #     - /var/lib/grafana:/var/lib/grafana
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=MYPASSWORT
            - GF_USERS_ALLOW_SIGN_UP=false
        ports: 
            - 3000:3000
        links: 
            - prometheus