- name: Copy compose file
  ansible.builtin.copy:
    src: ./docker-compose.yml
    dest: /root/docker-compose.yml
    owner: root
    group: root
    mode: "0644"

- name: Up Docker Containers
  command: chdir=/root docker-compose up -d