- name: Add Docker GPG Key - Ubuntu
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker Repository To apt - Ubuntu
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
- name: Install Docker - Ubuntu
  apt:
    name: docker-ce
    state: latest
    update_cache: yes

- name: Install Docker Compose
  command: curl -L https://github.com/docker/compose/releases/download/1.25.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose

- name: Make Docker Compose Executable
  command: chmod +x /usr/local/bin/docker-compose